### Monte Carlo Simulation:

The following notebook will take you through a simulation of levels of expected improvement on a known baseline for a set of random KPIs.

In [26]:
import pandas as pd
import numpy as np
import random

In [27]:
# Generate baseline metrics at random:

mnthly_revenue = random.randint(100000, 200000)
mnthly_churn = random.randint(12000, 15000)
mnthly_acquisitions = random.randint(10000, 20000)
customer_satisfaction = random.randint(10, 30)


baseline_df = pd.DataFrame({'Mnthly_Rev':mnthly_revenue, 'Mnthly_Churn':mnthly_churn, 'Mnthly_Acquisitions':mnthly_acquisitions, 'Customer_Satifaction':customer_satisfaction}, index = ['Baseline'])

# Transpose and store for later use:
baseline_df_tranposed = baseline_df.T.reset_index()

# Rename columns as desired:
baseline_df_tranposed.columns = ['Metric', 'Baseline']

baseline_df_tranposed

                 Metric  Baseline
0            Mnthly_Rev    127452
1          Mnthly_Churn     12686
2   Mnthly_Acquisitions     19106
3  Customer_Satifaction        14

In [28]:
# run the simulation for 2% improvement:
sim_no = 10000

# Store results
simulation_results_2_pct = []

for i in range(sim_no):
    factors = []
    for col in baseline_df.columns:
        if col in [mnthly_churn]:
            factor = np.random.uniform(0.99, 0.98) # reducing mnthly_churn by up to 1-2%
        else:
            factor = np.random.uniform(1.01, 1.02) # increasing other metrics by 1-2%
        factors.append(factor)

    simulated_values = baseline_df.iloc[0] * np.array(factors)
    simulation_results_2_pct.append(simulated_values)

 

# Convert results to DataFrame
simulation_df_2pct = pd.DataFrame(simulation_results_2_pct, columns=baseline_df.columns)

# Summary statistics
baseline_2pct = simulation_df_2pct.mean().round(2)

baseline_2pct_df =  pd.DataFrame({'Metric':baseline_2pct.index, '2pct':baseline_2pct.values})

baseline_2pct_df

                 Metric       2pct
0            Mnthly_Rev  129370.10
1          Mnthly_Churn   12875.87
2   Mnthly_Acquisitions   19392.55
3  Customer_Satifaction      14.21

In [29]:
# run the simulation for 5% improvement:
sim_no = 10000

# Store results
simulation_results_5_pct = []

for i in range(sim_no):
    factors = []
    for col in baseline_df.columns:
        if col in [mnthly_churn]:
            factor = np.random.uniform(0.95, 0.94) # reducing mnthly_churn by up to 4-5%
        else:
            factor = np.random.uniform(1.04, 1.05) # increasing other metrics by 4-5%
        factors.append(factor)

    simulated_values = baseline_df.iloc[0] * np.array(factors)
    simulation_results_5_pct.append(simulated_values)

 

# Convert results to DataFrame
simulation_df_5pct = pd.DataFrame(simulation_results_5_pct, columns=baseline_df.columns)

# Summary statistics
baseline_5pct = simulation_df_5pct.mean().round(2)

baseline_5pct_df =  pd.DataFrame({'Metric':baseline_5pct.index, '5pct':baseline_5pct.values})

baseline_5pct_df

                 Metric       5pct
0            Mnthly_Rev  133185.34
1          Mnthly_Churn   13256.71
2   Mnthly_Acquisitions   19964.57
3  Customer_Satifaction      14.63

In [30]:
# Join the resultant dataframes together:
Output_df = baseline_df_tranposed.merge(baseline_2pct_df, on='Metric').merge(baseline_5pct_df, on='Metric')

Output_df

                 Metric  Baseline       2pct       5pct
0            Mnthly_Rev    127452  129370.10  133185.34
1          Mnthly_Churn     12686   12875.87   13256.71
2   Mnthly_Acquisitions     19106   19392.55   19964.57
3  Customer_Satifaction        14      14.21      14.63